### ISSUE TITLE
Plugin confuses regular .HTML files

### ISSUE THREAD

**Issue by SanderFlooris** [Konafets/antlers-idea#113]
It seems like the plugin currently confuses PhpStorm if you have the plugin enabled and try to edit a regular .HTML file.
Code highlighting and executing the comment shortcut do not function correctly.

**Plugin disabled**
<img width="695" alt="Scherm­afbeelding 2023-02-27 om 09 51 34" src="https://user-images.githubusercontent.com/116890267/221517169-979b302f-24e8-4c59-bf85-abc9813f6724.png">

**Plugin enabled**
<img width="776" alt="Scherm­afbeelding 2023-02-27 om 09 50 49" src="https://user-images.githubusercontent.com/116890267/221517005-9c0ea84a-1de7-4b12-bff7-cf9936775495.png">

I don't know how this plugin exactly works, but maybe the file extension pattern is incorrect?
This has been tested using a scratch file on PhpStorm 2022.2.4 with plugin version 0.0.5.

**Comment by Konafets** [comment]
I could not reproduce the missing highlighting but the wrong commenting. I fixed it in a way that the plugin ignores `.html` files.
