### ISSUE TITLE
Move Antlers down in new file menu

### ISSUE THREAD

**Issue by marcorieser** [Konafets/antlers-idea#117]
When opening the "new file menu" Antlers is at the very top. This seems a bit pushy to me. I'd prefer it at least below `Directory`.
![Bildschirm­foto 2023-03-02 um 20 30 15](https://user-images.githubusercontent.com/2395800/222533130-f51302ca-c30d-4cdf-9124-6794fd3ba755.png)

**Comment by Konafets** [comment]
Moved the action to the place before the delimiter
<img width="215" alt="2023-03-09_20-55-41" src="https://user-images.githubusercontent.com/363363/224219644-36684642-8558-44bc-a4c0-6249a8362335.png">

**Comment by marcorieser** [comment]
Thank you, mich better ☺️
