### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by patrikkernke** [Konafets/antlers-idea#118]
The last days I have very bad performance issues when activating the plugin. They are so bad, that every typing or moving with keys has lags of 2-3secs or more. 

I love the plugin, but under this circumstances I can not use it. After deactivating the plugin the performance issues are gone.

**Comment by Konafets** [comment]
Hi @patrikkernke,

can you add your OS and version of PhpStorm, so I can test. Did the performance issues started with the latest version (0.0.5) or did you experienced them also before?

**Comment by Konafets** [comment]
Closed due to no response after four weeks.
