### ISSUE TITLE
Brackets are not correctly added when nested.

### ISSUE THREAD

**Issue by martyf** [Konafets/antlers-idea#39]
When the Antlers plugin is enabled, the code formatting, indenting and brackets as you type is not working correctly. 

**PhpStorm version**
PhpStorm 2022.2.1 Preview
Build #PS-222.3739.28, built on August 5, 2022
(using EAP for the UI Preview program)

**Video of issue**
https://www.awesomescreenshot.com/video/10406461?key=5c7ca37705ea5526a79c6935abb8a3c0

Interesting notes:
1. First use of `{{` appears to work correctly - it creates the correct double closing
2. Use a div, then try `{{` and you only get one `}` - expected `}}`
3. Outside (and after) the div, try `{{` and you get three `}}}` closing brackets

I see there is already issue #19 regarding indentation too - was able to confirm incorrect indentation.

**Comment by Konafets** [comment]
Fixed in bbf01f0e1492f816b15b33d4bb839de7b2e03e21
