### ISSUE TITLE
Reformat code indents the code badly

### ISSUE THREAD

**Issue by dominikkaluza** [Konafets/antlers-idea#74]
Hi, when I use the reformat code function in .antlers.html file, it reformats my code badly. I'm not sure what causes this behaviour because I think it was working for me fine before. Could you please help me navigate this issue?

I tried on both the latest released version 0.0.4 and the latest main.

Before reformat:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/38032505/215324280-7b36f236-dc3a-4a30-985c-26b8ffb82392.png">

After reformat:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/38032505/215324292-c67ff69e-7f0e-4dca-9cf3-e470ea7990e4.png">

**Comment by dadaxr** [comment]
Same here ... It's actually one of the most annoying bug to me right now ;)
Still a great plugin though !

**Comment by hlorofos** [comment]
Formatting sucks, that's one of the reason I've tried the plugin.

**Comment by Konafets** [comment]
Hey, 

thanks for the comments. I worked this very issue and its already solved in main branch, but I need to fix some other issues regarding formatting before I can release a new version. Stay tuned.

**Comment by weogrim** [comment]
@Konafets Can you in mean time maybe provide .jar file for main branch? I don't find it anywhere and this bug is really annoying ;). Unfortunately my knowledge about java/kotlin to little, to compile it myself.

**Comment by dominikkaluza** [comment]
@Konafets Hey, that's great to hear! :) Thank you for your work!

@weogrim You can download the latest built main here: https://github.com/Konafets/antlers-idea/actions/runs/4074535979 in the Artifacts section :)

**Comment by Konafets** [comment]
Hey,

the formatting faces two issues (as far as I know) currently:

- it adds spaces around equal signs in parameter list of an Antlers node
- it does not add spaces after the opening delimiter and before the closing delimiter `{{foo}}` stays `{{foo}}` instead of `{{ foo }}`

I am on a van trip right know with mostly no internet connectivity but I can assure you that this will definitely be fixed in next version.

**Comment by Konafets** [comment]
Fixed in version 0.0.5
